### ISSUE TITLE
okhttp connecting websocket with customized certificate

### ISSUE THREAD

**Issue by westchennnUVa** [commonsguy/cwac-netsecurity#15]
Hi, I saw how you did to bind customized certificate with HTTP connection, I tried to use this library to connect to secure websocket connection (wss://). But it always fail to bind the certificate if I used the same way. But I thought wss should be the same as https. Can you give me some clue how to bind customized certificate with websocket connection?

Thanks in advance!

**Comment by commonsguy** [comment]
Android itself does not support WebSockets outside of `WebView`, and `WebView` does not go through this library. I have not tried OkHttp + WebSockets + this library. Perhaps use [its own certificate customization support](https://github.com/square/okhttp/wiki/HTTPS#customizing-trusted-certificates) rather than this library.

**Comment by westchennnUVa** [comment]
Thank you for your quick response! I'll try that!
