### ISSUE TITLE
Could not resolve com.commonsware.cwac:netsecurity:0.4.5

### ISSUE THREAD

**Issue by jiaoyang28** [commonsguy/cwac-netsecurity#22]
Hi,

Our project is using com.commonsware.cwac:netsecurity:0.4.5, and it built successfully until Dec. 7th 2021.

Now, when we trigger the build, we got this error:
` > Could not resolve com.commonsware.cwac:netsecurity:0.4.5.
      > Could not get resource 'http://dl.bintray.com/amulyakhare/maven/com/commonsware/cwac/netsecurity/0.4.5/netsecurity-0.4.5.pom'.
         > Could not HEAD 'http://dl.bintray.com/amulyakhare/maven/com/commonsware/cwac/netsecurity/0.4.5/netsecurity-0.4.5.pom'. Received status code 502 from server: Bad Gateway
`
Actually, com.commonsware.cwac.security is not accessible, either.

May I ask you to check it up? 

Thank you very much.

**Comment by commonsguy** [comment]
That is not my artifact. You have been using somebody else's artifact, using the same Maven coordinates but in somebody else's Maven repository.

Your primary option is to either fork this repo or otherwise copy the code. As is noted on the project home page, this project is discontinued.

Otherwise, please follow the instructions from the project home page, where it shows the repository where my artifacts are published:

```gradle
repositories {
    maven {
        url "https://s3.amazonaws.com/repo.commonsware.com"
    }
}
```
